<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '68482350fa44c26e86072c0c092c9b64' => $baseDir . '/src/helpers.php',
    '000467475303963192ee9659379eca70' => $baseDir . '/src/setup.php',
    'dc79300a7254da9d49455aea9e385033' => $baseDir . '/src/filters.php',
    '4182fd7e7ccfa463004b753f88914c38' => $baseDir . '/src/admin.php',
    'c16d60b5d391cbf3ef29a8187496761a' => $baseDir . '/src/wp_bootstrap_navwalker.php',
);
